name: 'Create Student Version'
description: 'Run book cleaning script and push to student version repo'

inputs:
  pull-token:
    description: 'The GitHub Personal Access Token for pulling from the curriculum-book repo'
    required: true
  push-token:
    description: 'The GitHub PAT for pushing to the curriculum-book-student repo'
    required: true

runs:
  using: "composite"
  steps:

    - name: checkout repo content
      uses: actions/checkout@v3 # checkout the repository content to github runner
      with:
        token: ${{ inputs.pull-token }}

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # install the python version needed
        
    - name: install python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: execute py script # run clean_book.py
      shell: bash
      run: python .github/workflows/clean_book.py
        
    - name: remove book cleaning workflow # no need to run it on the student version, since we handled it already
      uses: JesseTG/rm@v1.0.3
      with:
        path: .github/workflows/clean.yaml

    - name: commit files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -a -m "cleaned books for student version" --allow-empty

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ inputs.push-token }}
        repository: geo-smart/curriculum-book-student
        branch: main 
        force: true