# If this is your first time using the environment,
# run `conda create --name ess490 --file conda-osx-64.lock`
# to get started.

# Once you have an environment created, you can edit this 
# file to add dependencies to environment, then run
# `conda activate ess490`
# followed by
# `conda env update --file environment.yml --prune`
# to update the environment.

name: curriculum_book
channels:
  - conda-forge
dependencies:
  - python=3.10
  - sphinxcontrib-bibtex
  - jupyter-book=0.13
  - jupytext
  - plotly=5.10.0
  - numpy
  - pandas
  # - pycaret # for chapter 3.8
platforms:
  - linux-64
  - osx-64
