name: Clean

on:
  push:
    paths:
      - 'book/**'
      - '.github/workflows/clean.yaml'
      - '.github/actions/**'

    branches:
      - main

jobs:
  clean-and-push:
    if: github.repository == 'geo-smart/curriculum-book'
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.CURRICULUM_BOOK_TOKEN }}

    - uses: ./.github/actions/studentversion
      with:
        key: ${{ secrets.STUDENT_BOOK_KEY }}
