name: Clean

on:
  push:
    paths:
      - 'book/**'
      - '.github/workflows/clean.yaml'
      - '.github/actions/**'

    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04

    steps:
    - uses: ./.github/actions/studentversion
      with:
        pull-token: ${{ secrets.CURRICULUM_BOOK_TOKEN }}
        push-token: ${{ secrets.STUDENT_BOOK_TOKEN }}
